### ISSUE TITLE
Mailer Service

### ISSUE THREAD

**Issue by Manav-Khandurie** [Manav-Khandurie/AgileTalks-WebChatApp-Microservices#4]
Create a service that sends the user a mail using Nodemailer

**Comment by satviktripathi369** [comment]
Confirmed sir, working on it.

**Comment by Manav-Khandurie** [comment]
Instead of using AWS SES we will be utilizing nodemailer with mailgun to send emails to the users

**Comment by tanmayy-mishra** [comment]
done manav.
